[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# File mapping configuration
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@market/=src/Market.sol",
    "@tokens/=src/",
    "@scripts/=script/",
    "@test/=test/",
    "@lib/=lib/"
]

# Solidity compiler settings
solc = "0.8.26"
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200

# Test settings
[fuzz]
runs = 1000
seed = '0x1'

[invariant]
runs = 1000
depth = 32
fail_on_revert = true

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = []

# Verbose output for better debugging
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
